#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
source "${SCRIPT_DIR}/common_env.sh"

export DEEPSCALER_DEBUG_DIR="${DEEPSCALER_SATURATION_PROBE_DIR}"
export DEEPSCALER_DEBUG_TRAIN_SIZE="${DEEPSCALER_SATURATION_PROBE_TRAIN_SIZE:-1000}"
export DEEPSCALER_DEBUG_TEST_SIZE="${DEEPSCALER_SATURATION_PROBE_TEST_SIZE:-200}"
export DEEPSCALER_DEBUG_LENGTH_LIMIT_TOKENS="${DEEPSCALER_SATURATION_PROBE_LENGTH_LIMIT_TOKENS:-4000}"

"${SCRIPT_DIR}/prepare_deepscaler_math.sh" "$@"
