#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
source "${SCRIPT_DIR}/common_env.sh"

sol_require_slurm_allocation
sol_ensure_runtime_dirs
sol_ensure_upstream_checkout
sol_activate_env

PROBE_DATASET_DIR="${DEEPSCALER_SATURATION_PROBE_DIR}"
[[ -f "${PROBE_DATASET_DIR}/train.parquet" ]] || {
  printf '[sol-setup] ERROR: Missing %s/train.parquet. Run scripts/sol/prepare_deepscaler_saturation_probe.sh first.\n' "${PROBE_DATASET_DIR}" >&2
  exit 1
}
[[ -f "${PROBE_DATASET_DIR}/test.parquet" ]] || {
  printf '[sol-setup] ERROR: Missing %s/test.parquet. Run scripts/sol/prepare_deepscaler_saturation_probe.sh first.\n' "${PROBE_DATASET_DIR}" >&2
  exit 1
}

export MATH_LENGTH_MODEL_PATH="${GDPO_SATURATION_PROBE_MATH_MODEL_PATH:-Qwen/Qwen2.5-0.5B-Instruct}"
export MATH_LENGTH_N_GPUS_PER_NODE="${GDPO_SATURATION_PROBE_N_GPUS_PER_NODE:-2}"
export MATH_LENGTH_NNODES="${GDPO_SATURATION_PROBE_NNODES:-1}"
export MATH_LENGTH_TRAIN_BATCH_SIZE="${GDPO_SATURATION_PROBE_TRAIN_BATCH_SIZE:-32}"
export MATH_LENGTH_VAL_BATCH_SIZE="${GDPO_SATURATION_PROBE_VAL_BATCH_SIZE:-16}"
export MATH_LENGTH_MAX_PROMPT_LENGTH="${GDPO_SATURATION_PROBE_MAX_PROMPT_LENGTH:-512}"
export MATH_LENGTH_MAX_RESPONSE_LENGTH="${GDPO_SATURATION_PROBE_MAX_RESPONSE_LENGTH:-5000}"
export MATH_LENGTH_LIMIT_TOKENS="${GDPO_SATURATION_PROBE_LENGTH_LIMIT_TOKENS:-4000}"
export MATH_LENGTH_ROLLOUT_N="${GDPO_SATURATION_PROBE_ROLLOUT_N:-4}"
export MATH_LENGTH_MAX_NUM_SEQS="${GDPO_SATURATION_PROBE_MAX_NUM_SEQS:-16}"
export MATH_LENGTH_MAX_NUM_BATCHED_TOKENS="${GDPO_SATURATION_PROBE_MAX_NUM_BATCHED_TOKENS:-10000}"
export MATH_LENGTH_GPU_MEMORY_UTILIZATION="${GDPO_SATURATION_PROBE_GPU_MEMORY_UTILIZATION:-0.50}"
export MATH_LENGTH_PPO_MINI_BATCH_SIZE="${GDPO_SATURATION_PROBE_PPO_MINI_BATCH_SIZE:-16}"
export MATH_LENGTH_PPO_MICRO_BATCH_SIZE="${GDPO_SATURATION_PROBE_PPO_MICRO_BATCH_SIZE:-2}"
export MATH_LENGTH_TOTAL_TRAINING_STEPS="${GDPO_SATURATION_PROBE_TOTAL_TRAINING_STEPS:-200}"
# 1000 prompts at batch size 32 only yields ~32 steps/epoch, so one epoch cannot reach 200 steps.
export MATH_LENGTH_TOTAL_EPOCHS="${GDPO_SATURATION_PROBE_TOTAL_EPOCHS:-8}"
export MATH_LENGTH_SAVE_FREQ="${GDPO_SATURATION_PROBE_SAVE_FREQ:-50}"
export MATH_LENGTH_TEST_FREQ="${GDPO_SATURATION_PROBE_TEST_FREQ:-25}"
export MATH_LENGTH_ENABLE_FILTER_GROUPS="False"
export MATH_LENGTH_PROJECT_NAME="${GDPO_SATURATION_PROBE_MATH_PROJECT_NAME:-${SOL_PROJECT_NAME}_gdpo_saturation_probe_math}"
export MATH_LENGTH_EXPERIMENT_NAME="${GDPO_SATURATION_PROBE_MATH_EXPERIMENT_NAME:-qwen2_5_0_5b_gdpo_saturation_probe_math}"
export DEEPSCALER_DEBUG_DIR="${PROBE_DATASET_DIR}"

"${SCRIPT_DIR}/run_math_length_common.sh" gdpo debug "$@"
