#!/usr/bin/env bash
# Config provenance:
# - Semantic baseline: modern GSM8K two-reward GDPO (`correct_reward + format_reward`).
# - Runtime profile: sol_fit_2gpu.
# - Entry type: short feasibility-smoke wrapper for the GSM8K fit-contract path on SOL.
# - Upstream anchors: external/verl/examples/tuning/3b/qwen2-3b_grpo-lora_1_h100_fsdp_vllm.sh and external/verl/examples/gdpo_trainer/run_qwen1_5b_gdpo.sh
# - Closest prior working local config: /Users/god/Documents/VERL_GRPO/scripts/sol/run_gdpo_gsm8k_modern_debug.sh
# - Historical failure reference: /Users/god/Documents/VERL_GRPO/docs/sol_rl_fit_error_catalog.md
# - Required manual gate before edits: /Users/god/Documents/VERL_GRPO/docs/sol_rl_fit_config_creation_checklist.md
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
source "${SCRIPT_DIR}/common_env.sh"

export GSM8K_MODERN_RUNTIME_PROFILE="${GSM8K_MODERN_RUNTIME_PROFILE:-sol_fit_2gpu}"
export GSM8K_MODERN_RUN_CLASSIFICATION="${GSM8K_MODERN_RUN_CLASSIFICATION:-feasibility-smoke}"
export GSM8K_MODERN_EXPERIMENT_NAME="${GSM8K_MODERN_EXPERIMENT_NAME:-qwen2_5_1_5b_instruct_gdpo_gsm8k_modern_fit_debug_answer_tag}"
export GSM8K_MODERN_PROJECT_NAME="${GSM8K_MODERN_PROJECT_NAME:-${SOL_PROJECT_NAME}_gdpo_gsm8k_modern_fit_debug_answer_tag_1_5b_instruct}"
export GSM8K_MODERN_MODEL_PATH="${GSM8K_MODERN_MODEL_PATH:-Qwen/Qwen2.5-1.5B-Instruct}"
export GSM8K_MODERN_N_GPUS_PER_NODE="${GSM8K_MODERN_N_GPUS_PER_NODE:-2}"
export GSM8K_MODERN_NNODES="${GSM8K_MODERN_NNODES:-1}"
export GSM8K_MODERN_TRAIN_BATCH_SIZE="${GSM8K_MODERN_TRAIN_BATCH_SIZE:-16}"
export GSM8K_MODERN_VAL_BATCH_SIZE="${GSM8K_MODERN_VAL_BATCH_SIZE:-16}"
export GSM8K_MODERN_MAX_PROMPT_LENGTH="${GSM8K_MODERN_MAX_PROMPT_LENGTH:-512}"
export GSM8K_MODERN_MAX_RESPONSE_LENGTH="${GSM8K_MODERN_MAX_RESPONSE_LENGTH:-1024}"
export GSM8K_MODERN_PPO_MINI_BATCH_SIZE="${GSM8K_MODERN_PPO_MINI_BATCH_SIZE:-16}"
export GSM8K_MODERN_PPO_MICRO_BATCH_SIZE="${GSM8K_MODERN_PPO_MICRO_BATCH_SIZE:-1}"
export GSM8K_MODERN_ROLLOUT_LOGPROB_MICRO_BATCH_SIZE="${GSM8K_MODERN_ROLLOUT_LOGPROB_MICRO_BATCH_SIZE:-1}"
export GSM8K_MODERN_REF_LOGPROB_MICRO_BATCH_SIZE="${GSM8K_MODERN_REF_LOGPROB_MICRO_BATCH_SIZE:-1}"
export GSM8K_MODERN_ROLLOUT_N="${GSM8K_MODERN_ROLLOUT_N:-4}"
export GSM8K_MODERN_LR="${GSM8K_MODERN_LR:-3e-6}"
export GSM8K_MODERN_TP_SIZE="${GSM8K_MODERN_TP_SIZE:-1}"
export GSM8K_MODERN_GPU_MEMORY_UTILIZATION="${GSM8K_MODERN_GPU_MEMORY_UTILIZATION:-0.35}"
export GSM8K_MODERN_MAX_MODEL_LEN="${GSM8K_MODERN_MAX_MODEL_LEN:-1536}"
export GSM8K_MODERN_MAX_NUM_BATCHED_TOKENS="${GSM8K_MODERN_MAX_NUM_BATCHED_TOKENS:-1536}"
export GSM8K_MODERN_MAX_NUM_SEQS="${GSM8K_MODERN_MAX_NUM_SEQS:-64}"
export GSM8K_MODERN_ENABLE_CHUNKED_PREFILL="${GSM8K_MODERN_ENABLE_CHUNKED_PREFILL:-False}"
export GSM8K_MODERN_USE_SHM="${GSM8K_MODERN_USE_SHM:-False}"
export GSM8K_MODERN_ACTOR_PARAM_OFFLOAD="${GSM8K_MODERN_ACTOR_PARAM_OFFLOAD:-True}"
export GSM8K_MODERN_ACTOR_OPTIMIZER_OFFLOAD="${GSM8K_MODERN_ACTOR_OPTIMIZER_OFFLOAD:-True}"
export GSM8K_MODERN_REF_PARAM_OFFLOAD="${GSM8K_MODERN_REF_PARAM_OFFLOAD:-True}"
export GSM8K_MODERN_SKIP_TOKENIZER_INIT="${GSM8K_MODERN_SKIP_TOKENIZER_INIT:-True}"
export GSM8K_MODERN_AGENT_NUM_WORKERS="${GSM8K_MODERN_AGENT_NUM_WORKERS:-1}"
export GSM8K_MODERN_TOTAL_TRAINING_STEPS="${GSM8K_MODERN_TOTAL_TRAINING_STEPS:-1}"
export GSM8K_MODERN_TOTAL_EPOCHS="${GSM8K_MODERN_TOTAL_EPOCHS:-1}"
export GSM8K_MODERN_SAVE_FREQ="${GSM8K_MODERN_SAVE_FREQ:-1}"
export GSM8K_MODERN_TEST_FREQ="${GSM8K_MODERN_TEST_FREQ:-1}"
export GSM8K_MODERN_VAL_BEFORE_TRAIN="${GSM8K_MODERN_VAL_BEFORE_TRAIN:-False}"
export GSM8K_MODERN_VAL_MAX_SAMPLES="${GSM8K_MODERN_VAL_MAX_SAMPLES:-64}"

exec "${SCRIPT_DIR}/run_gdpo_gsm8k_modern_fit_2gpu.sh" "$@"
